### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by synvatto**
pls dont send pull requests

### CODE REVIEW

**Comment by code-nightfall** [comment]
Punda punda punda

**Comment by Luke-6723** [comment]
Whats the use for this on the issues page? Top.gg has https://feedback.top.gg for bug reports.

If you have a security concern you can contact one of the Team members / iara should you have a serious concern. Though I do not see a need for this on the top.gg issues repo to be completely honest

**Review by DolceJ0Lly — CHANGES_REQUESTED** [review]
No

**Comment by code-nightfall** [comment]
naw

**Pull request closed without merging**
